### ISSUE TITLE
Output HaploPainter extended pedigree file

### ISSUE THREAD

**Issue by the-x-at** [EuracBiomedicalResearch/FamAgg#13]
Function `plotPed` with prior call to `switchPlotfun("haplopaint")` generates a temporary file that is supplied to HaploPainter program. It would be desirable to retrieve this file by some means for manual editing and fine tuning with HaploPainter GUI, e.g. with a new option `dev="csv"`.

**Comment by the-x-at** [comment]
A nice addon would be a header line as a comment that describes (also tab-separated) each column, as there are many of them. E.g.
`#FAMID INDIVID DADID MOMID GENDER AFF DEAD SABTOP PROBAND ADOPT TWINS CONSAN TINSYM TBESSYM T1UNDR T2UNDR T3UNDR T4UNDR`
It is not part of the LINKAGE file format, but HaploPainter explicitly allows comments. Therefore, this information would be helpful when editing the file.

**Comment by jorainer** [comment]
and what about defining an explicit function `export...` that saves the info in the haplopainter format?

**Comment by the-x-at** [comment]
Would that then imply an interface duplication to what can be supplied to `plotPed`? I am talking about all the fancy parameters like `text.beside.symbol`, `textN.below.symbol`, etc. I see them as a nice way to streamline plotting and use HaploPainter GUI only as the very last step for fine tuning.

**Comment by jorainer** [comment]
You're right. Makes no sense to add all these additional columns to an `export` call. I like the idea of a `device = "csv"` - eventually we should also add a `device = "dev/null"` too :)

**Comment by jorainer** [comment]
OK, `device = "txt"` writes the results (including header) to a file and the function returns then the name of that file.

**Comment by jorainer** [comment]
Fix is in - have a look at it and merge if you're happy @the-x-at

**Comment by jorainer** [comment]
Done and pushed to Bioconductor. Closing.
