### ISSUE TITLE
Argument "main=" not used/causes error in plotPed

### ISSUE THREAD

**Issue by the-x-at** [EuracBiomedicalResearch/FamAgg#16]
According to the documentation of `plotPed`, argument `main` should be passed on to `doPlotPed`, where it is explicitly listed as an argument (`main=NULL`). Using this argument results in undesired behavior, as demonstrated by the following example:

    library(FamAgg)
    data("minnbreast")
    family <- minnbreast[minnbreast$famid==4, ]
    mbped <- family[, c("famid", "id", "fatherid", "motherid", "sex")]
    colnames(mbped) <- c("family", "id", "father", "mother", "sex")
    fad <- FAData(pedigree=mbped)
    switchPlotfun("haplopaint")
    plotPed(fad, family=4, device="png", filename="~/works.png")
    ## "Error in expected number of arguments!"
    plotPed(fad, family=4, device="png", main="My title", filename="~/error.png")
    switchPlotfun("ks2paint")
    ## String "My title" does not show up in image.
    plotPed(fad, family=4, device="png", main="My title", filename="~/works-a-bit.png")

* Use of `main="My title"` in plotting mode `haplopaint` causes an error message and no plot output file is generated.

* Use of `main="My title"` in plotting mode `ks2paint` does not show the text in the plot.

* Not using `main` option in plotting mode `haplopaint` outputs by default the family number.

FamAgg version 1.8.0 was used.

**Comment by jorainer** [comment]
passing `main` down to haplopaint with the `-family` parameter. Will check if that needs eventually special formatting.

**Comment by jorainer** [comment]
OK, `plot.pedigree` from the `kinship2` package simply ignores the `main` parameter. No way we can define a title in plots created with that (will change the documentation on that).

Re haplopaint, I am now quoting the `-family` command line parameter. It should work now (version 1.9.1), but I can't verify because haplopaint is missing a lot of dependencies on my system - @the-x-at can you please check?

**Comment by the-x-at** [comment]
The `haplopainter` script expects a family number as parameter to option `-family`. This will not work for supplying generic text. I checked the haplopainter source, there is no way to add a plot title from the command line. It can only be done in the GUI with Options->Configuration->Ped & Case Info->Title.

Now, that neither `haplopainter` nor the `kinship2` plotting functions accept a title, I recommend to remove option `main=` from the plotting options for `doPlotPed`.

Alternatively, I could modify `haplopainter` source code to accept an option `-title`.

**Comment by jorainer** [comment]
OK, then I'll remove the `main` parameter.

**Comment by jorainer** [comment]
Done in https://github.com/EuracBiomedicalResearch/FamAgg/commit/ef11e8ab02d5f72bc2d61926f98af4551930824f
