### ISSUE TITLE
Logical trait assignment fails

### ISSUE THREAD

**Issue by the-x-at** [EuracBiomedicalResearch/FamAgg#20]
Using a `logical` named vector for affection status in either the constructor of `FAData` or the setter function `trait<-` results in the following error message: _trait has to be a named vector with the names corresponding to the IDs used in the pedigree_. This is due to a missing reassignment of names that are dropped upon conversion of the `logical` vector to `numeric` in the setter method.

**Comment by jorainer** [comment]
Do you have a fix for this? Please wait some minutes until I have synced the current master with bioconductor.

**Comment by jorainer** [comment]
Ah, I did that already today morning.

**Comment by the-x-at** [comment]
The fix is straightforward, one has to reassign the names in the vector. If the `FAData` constructor calls the `trait<-` setter method, this is a one-liner.

**Comment by jorainer** [comment]
Merged and pushed also to Bioconductor.

**Comment by the-x-at** [comment]
So long and thanks for all the fish.
